version: '3.8'

services:
  api:
    build:
      context: .
      target: develop
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - blog

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5433:${DB_PORT}
    volumes:
      - dbdata:/db/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - blog

  redis:
    image: 'redis:alpine'
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/data
    ports:
      - '6379:6379'
    networks:
      - blog


volumes:
  dbdata: {}

networks:
  blog: